// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Sidebar } from '@/components/Sidebar'; // Importe a Sidebar

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'App com Sidebar',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className={inter.className}>
        {/* Container principal usando Flexbox */}
        <div className="flex">
          {/* A Sidebar com largura fixa */}
          <Sidebar />

          {/* Área de conteúdo principal que cresce para preencher o espaço */}
          <div className="flex-1 h-screen bg-gray-50">
            {/* O conteúdo da página atual será renderizado aqui */}
            <div className="p-8">
              {children}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}